### ISSUE TITLE
Offline status not updated

### ISSUE THREAD

**Issue by andres-lago** [QuickBlox/q-municate-ios#126]
When one user logs out, the other users continue to see them in 'online' instead of 'offline'. In the test, only after 20 minutes the correct status appeared.

To reproduce the error: 
1)Run app in simulator, login as user A with Facebook
2)Run app in iPhone 5s, login as user B
3)From each app, add user as contact user A or B 
4)In app (1),  logout user A
5)In app (2) The status for user A should appear as 'offline', instead we can see the 'online' label in several views (Contacts, Contact details, ...)
  
q-comunicate version: 29/Feb/2016
IOS version (iPhone): 9.2.1
IOS version (sim): 8.4

**Comment by Raikerian** [comment]
Hi,

There is no version from 26/Feb/2016
We have an 29/Feb/2016 version in master.

However I was able to reproduce this issue and it seems the issue is server-sided. We are currently investigating this and will post update soon.

**Comment by Raikerian** [comment]
There was some server-side problems yesterday and everything is working for me today. Can you confirm this?

**Comment by andres-lago** [comment]
Perfect, I confirm it's working Ok. I feel the messages are dispatched quicker too. On the other side, I hope this server problem doesn't repeat frequently. For users is frustrating waiting for an answer that will never arrive. Thanks for the quick reply.
