### ISSUE TITLE
After login, I am unable to do anything. 

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/q-municate-ios#128]
Only below screen is occured.

![simulator screen shot mar 25 2016 12 50 57 pm](https://cloud.githubusercontent.com/assets/12935350/14039978/80a791de-f288-11e5-8d03-33c2aed9deea.png)

How to add friends and chat.
Thanks

**Comment by dmit2k** [comment]
Hi! How did you solve this? Searching both Local and Global shows nothing in all apps...
