### ISSUE TITLE
Upgrade to last SDK version

### ISSUE THREAD

**Issue by andres-lago** [QuickBlox/q-municate-ios#131]
Hi,
  I'm evaluating your solution. Q-Communicate would be a possible app to reuse but the problem is that it's using a previous QuickBlox SDK, version 2.6.5. Current SDK version is v2.7. Migrating to v2.7 requires some extra work, not convenient for me. In order to going forward with the decision, could you please help with some answers:  
  -Till what date will you accept in the server requests from version 2.6.5?
  -Any requests/functions implemented in v2.6.5 have become out of service?

 Thanks.

**Comment by iSevenDays** [comment]
Hi @andres-lago ,

We have long term support of SDK versions and we do not force you to upgrade, but new features and bug fixes will be available only to new SDKs.

>> -Till what date will you accept in the server requests from version 2.6.5?
>> -Any requests/functions implemented in v2.6.5 have become out of service?

We don't plan to stop supporting 2.x.x SDK.  You can run even 2.2-2.3, but it is not recommended.


Thanks!
