### ISSUE TITLE
Problem adding contacts

### ISSUE THREAD

**Issue by dmit2k** [QuickBlox/q-municate-ios#164]
Wanted to try the platform and the app, registered by phone on one iOS device, by FaceBook on another, and by e-mail from web app.

Now absolutely unclear how to add the contacts to each other instance.

**Comment by Raikerian** [comment]
Hi,

I can only answer iOS part of question, just open contacts tab and tap on search. You can find users and add them in global search scope.

**Comment by dmit2k** [comment]
I tried, but can't find myself from another ios device. What should I use for search keyword - my Facebook profile name or what is set in my profile within the app? If one of my devices was registered by phone number - should I use this number to find a contact or by what was set in the app profile?

Anyway, neither works... Whatever I do I can't find my other device.

**Comment by Raikerian** [comment]
You should search for Q-municate user full name.

**Comment by dmit2k** [comment]
OK, got it working on ios, global search is terribly slow...

Still having problems finding both ios devices from browser app

**Comment by Raikerian** [comment]
Please, report web-related problems to a specific repository: https://github.com/QuickBlox/q-municate-web

**Comment by dmit2k** [comment]
Thank you!
