### ISSUE TITLE
Recent Dialog List TableView not returning any value

### ISSUE THREAD

**Issue by xeravim** [QuickBlox/q-municate-ios#167]
Hi I have been trying to move the placement of "Chat" Tab to second tab, and the tableview not return anything if it placed on the second.. but If I put it to the first tab, it works normal...

Why is this happening?

**Comment by Raikerian** [comment]
Hi,

Try to call tableView reloadData method, it is probably happening because data source for dialogs been configured while controller is not on screen.

**Comment by xeravim** [comment]
Hi,

I have been calling reload data at all over the place on QMDialogsViewController, but still no effect..

I have put reloadData here on QMDialogsViewController

    - (void)configureDataSources {
    
    self.dialogsDataSource = [[QMDialogsDataSource alloc] init];
    self.placeholderDataSource  = [[QMPlaceholderDataSource alloc] init];
    
    self.tableView.dataSource = self.placeholderDataSource;
    
    QMDialogsSearchDataProvider *searchDataProvider = [[QMDialogsSearchDataProvider alloc] init];
    searchDataProvider.delegate = self.searchResultsController;
    
    self.dialogsSearchDataSource = [[QMDialogsSearchDataSource alloc] initWithSearchDataProvider:searchDataProvider];
  NSLog(@"item :%lu",(unsigned long)_dialogsDataSource.items.count); // Items are filled, but reloadData do not make them show on the Table View
  [self.tableView reloadData];
}

**Comment by xeravim** [comment]
Or maybe it should be another controller reloadData that I should called?

**Comment by Raikerian** [comment]
Check what data source you are getting. It should be QMDialogsDataSource.

**Comment by xeravim** [comment]
It solved by referencing self.tableView.dataSource = self.dialogsDataSource

Thanks Raikerian!
