### ISSUE TITLE
I have Installed the pods but QMServicesDevelopment Pod not get installed. And When I try to integrate Core classes of Q-municate Project it gives the error "Expected a type" for QB_NULLABLE.

### ISSUE THREAD

**Issue by rkumawat** [QuickBlox/q-municate-ios#170]
Kindly suggest me the steps how to integrate and what classes to be integrated to use QuickBlox Chat and Video feature in my Project.

**Comment by Pro100Andrey** [comment]
Hi @rkumawat 
1. [How to create your QuickBlox account] (http://quickblox.com/developers/5_Minute_Guide#Create_your_QuickBlox_account)
2. [How to connect Quickblox framework] (http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework)
3. [Check Chat Sample](http://quickblox.com/developers/SimpleSample-chat_users-ios)
4. [Check Video / Audio sample] (http://quickblox.com/developers/Sample-webrtc-ios)

About your error:
Please add in your pod file:

```
pod 'QuickBlox'
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :branch => 'development'
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development'
```

**Comment by Pro100Andrey** [comment]
Hi @rkumawat. Any updates ?

**Comment by Raikerian** [comment]
@rkumawat 

We haven't hear any updates from you, if you are still experiencing this issue- just reopen it. If you have any other problems, feel free to create a separate issue.

**Comment by KuriakosePious** [comment]
[!] Error installing QMCVDevelopment
[!] /usr/bin/git clone git@github.com:QuickBlox/QMChatViewController-ios.git /var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-10605-irwj1h --template= --single-branch --depth 1 --branch development

Cloning into '/var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-10605-irwj1h'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by Kuriakose3** [comment]
@Pro100Andrey  @Raikerian  

[!] Error installing QMCVDevelopment
[!] /usr/bin/git clone git@github.com:QuickBlox/QMChatViewController-ios.git /var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-10605-irwj1h --template= --single-branch --depth 1 --branch development

Cloning into '/var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-10605-irwj1h'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Kuriakose3** [comment]
@VitaliyGuru  @Pro100Andrey  @Raikerian  getting this warning
Hi Kuriakose3! You've successfully authenticated, but GitHub does not provide shell access.
