### ISSUE TITLE
After login, I am unable fetch my local (Device) Contacts

### ISSUE THREAD

**Issue by aanchalkalani** [QuickBlox/q-municate-ios#175]
![simulator screen shot jul 11 2016 4 03 26 pm](https://cloud.githubusercontent.com/assets/6301399/16727906/054d684e-4781-11e6-8c42-7cb6cd85eb11.png)

Hi,

We are unable to fetch the device contact list the iOS application. 

1. We allowed in settings of our application(Web) to download users :- Check "Allow to retrieve a list of users".
2. We search the users Locally and Globally but nothing happens.  

Any help would be appreciated. 

Thanks,

**Comment by Raikerian** [comment]
Hi,

There is no such feature as fetching device contact list. That contact list represents your Quickblox contact list.

**Comment by Loborro** [comment]
Its easy, just go to your quickblox admin panel, click to your app, in overview, in the corner, there is a tab that say SETTINGS, in this secction mark the combobox that say "Allow to retrieve a list of users".

**Comment by Raikerian** [comment]
If you have any other questions, feel free to let us know by creating a separate issue.
