### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by Shamsiddin** [QuickBlox/q-municate-ios#18]
I don't know what is the problem but I'm not able to build it with XCode 6.3. It's giving me errors on many places.
My OS X Version is: 10.11 (15A282b) El Capitan.

Can You please give me any solution to build it successfully. That would be good practise for my project.

Thanks.

**Comment by Raikerian** [comment]
Hi,

Please show your errors or explain it with more details so we can try to help you.

**Comment by Shamsiddin** [comment]
Hi, 
Thank you for your response. My problem was solved. It turns out error was when I opened project from remote computer folder. When I copied it locally and built it worked.
