### ISSUE TITLE
Can not run QMServices 0.4.4

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-ios#183]
Here is the error after update to 0.4.4
<img width="1381" alt="screen shot 2016-08-17 at 9 48 34 am" src="https://cloud.githubusercontent.com/assets/1511264/17722899/f09ee8f4-645f-11e6-903f-d36222cfd2a9.png">

**Comment by VitaliyGuru** [comment]
@tranngoclinh88 Have you fixed this issue?

**Comment by tranngoclinh88** [comment]
No. I'm using 0.4.3.
