### ISSUE TITLE
Dialogs cache issue

### ISSUE THREAD

**Issue by phiren** [QuickBlox/q-municate-ios#195]
Hello,

Below code returns 0 dialogs even though there are two dialogs exist. (Both are public dialog)
`func dialogs() -> [QBChatDialog]? { return ServicesManager.instance().chatService.dialogsMemoryStorage.dialogsSortByUpdatedAtWithAscending(false) }
`
While if use below code, it returns two dialogs

```
ServicesManager.instance().cachedDialogs { (dialogs) in

}

```
Not sure, What's going wrong.

**Comment by phiren** [comment]
The problem might be with public dialog only, not sure still i have not tested 1-1 chat, but here is my workaround to solve above problem:

Class : QMChatServices.m

Function: loadCachedDialogsWithCompletion
Changed it with below wayL
`
- (void)loadCachedDialogsWithCompletion:(dispatch_block_t)completion {
    
    __weak __typeof(self)weakSelf = self;
    
    if ([self.cacheDataSource respondsToSelector:@selector(cachedDialogs:)]) {
        
        NSAssert(self.serviceManager.currentUser != nil, @"Current user must be non nil!");
        
        [weakSelf.cacheDataSource cachedDialogs:^(NSArray *collection) {
            
            if (collection.count > 0) {
                // We need only current users dialog
                
//                NSArray *userDialogs = [collection filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"%lu IN self.occupantIDs", self.serviceManager.currentUser.ID]];
                
                [weakSelf.dialogsMemoryStorage addChatDialogs:collection andJoin:self.isAutoJoinEnabled];
                
                if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didAddChatDialogsToMemoryStorage:)]) {
                    [weakSelf.multicastDelegate chatService:weakSelf didAddChatDialogsToMemoryStorage:collection];
                }
                
                NSMutableSet *dialogsUsersIDs = [NSMutableSet set];
                for (QBChatDialog *dialog in collection) {
                    [dialogsUsersIDs addObjectsFromArray:dialog.occupantIDs];
                }
                if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didLoadChatDialogsFromCache:withUsers:)]) {
                    [weakSelf.multicastDelegate chatService:weakSelf didLoadChatDialogsFromCache:collection withUsers:dialogsUsersIDs.copy];
                }
            }
            
            /*
            if (collection.count > 0) {
                // We need only current users dialog
                
                NSArray *userDialogs = [collection filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"%lu IN self.occupantIDs", self.serviceManager.currentUser.ID]];
                
                [weakSelf.dialogsMemoryStorage addChatDialogs:userDialogs andJoin:NO];
                
                if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didAddChatDialogsToMemoryStorage:)]) {
                    [weakSelf.multicastDelegate chatService:weakSelf didAddChatDialogsToMemoryStorage:collection];
                }
                
                NSMutableSet *dialogsUsersIDs = [NSMutableSet set];
                for (QBChatDialog *dialog in userDialogs) {
                    [dialogsUsersIDs addObjectsFromArray:dialog.occupantIDs];
                }
                if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didLoadChatDialogsFromCache:withUsers:)]) {
                    [weakSelf.multicastDelegate chatService:weakSelf didLoadChatDialogsFromCache:userDialogs withUsers:dialogsUsersIDs.copy];
                }
            }
            /*/
             
            if (completion) {
                completion();
            }
        }];
    }
}

`

Not sure this is right way or not, but now it shows cached dialogs too.

**Comment by nectarbits** [comment]
after installing pod in new demo project , here it says that , #import < Quickblox/Quickblox.h > not found in QBChatMessage+QBDateDivider.h file

now , what to do ?

**Comment by Raikerian** [comment]
Hi @phiren 

There is no support for public chats at this moment. You can use your own fix fow now.
