### ISSUE TITLE
#import <Quickblox/Quickblox.h> not found

### ISSUE THREAD

**Issue by nectarbits** [QuickBlox/q-municate-ios#196]
Steps for issue 

download (https://github.com/QuickBlox/q-municate-ios)
create new demo application  
add new pod file  
copy all pod listed in downloaded project ,  
copy in pod file  , created in new demo application ,  
install pod (using github account) 

Run application 
here it says that , #import < Quickblox/Quickblox.h > not found  in QBChatMessage+QBDateDivider.h file

**Comment by Raikerian** [comment]
Hi,

Why are you creating a new podfile and what is the reasoning behind not using ours?

**Comment by nectarbits** [comment]
We have a project where chat is one module out of major 10 modules.
which require One to One Chat and Group chat with text , image , video , product and link sharing features so we have to import whole your project into our project so our other module also don't affect. 

So kindly provide the suggestion why we are facing above issue. 

Your help will be appreciated. Looing forward for your response.

**Comment by Raikerian** [comment]
Have you installed Quickblox framework? Through pods or manual installation ([details](http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework)).

**Comment by nectarbits** [comment]
i just copy Quickblox framwork package from Q-municate framwork folder . and drag in demo application framwork folder ,

**Comment by Raikerian** [comment]
You can't just drag and drop framework into project folder to make it work, please follow our installation steps here: http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework

**Comment by VitaliyGuru** [comment]
@nectarbits  Any updates?

**Comment by nectarbits** [comment]
HI, Finally we successfully migrated into our development. Now we would like to utilize for video and link sharing. DO you have any idea how we can do that ?

**Comment by VitaliyGuru** [comment]
@nectarbits Could you please create a new issue for your questions?
Closing this for now.
