### ISSUE TITLE
How to hang up a single user from conference call?

### ISSUE THREAD

**Issue by heavyBug** [QuickBlox/q-municate-ios#199]
I have seen a function in Android SDK 
public void procHangUpOpponent(Integer opponentID,
                      Map<String,String> userInfo)
Close channel with concrete opponent
Parameters:
opponentID -

But there is no any method in ios SDK which can be called to hang up a specific user.

Any help will be appreciated

**Comment by Raikerian** [comment]
This issue is related to an SDK and you've already created it there: https://github.com/QuickBlox/quickblox-ios-sdk/issues/665

Let's stick to one thread.

**Comment by heavyBug** [comment]
Thanks for immediate reply but I am in trubble ... You have used it
if you can help me

**Comment by Pro100Andrey** [comment]
Hi @heavyBug, [Use this method of delegate](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/Framework/QuickbloxWebRTC.framework/Versions/A/Headers/QBRTCClientDelegate.h#L82)

**Comment by Raikerian** [comment]
Stick to the main issue here: https://github.com/QuickBlox/quickblox-ios-sdk/issues/665
