### ISSUE TITLE
QMServicesDevelopment/QMDBStorage/QMDBStorage/QMCDRecord/Categories/CoreData/NSManagedObjectModel+QMCDRecord.h:16:120: Expected identifier

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/q-municate-ios#201]
Getting Error in NSManagedObjectModel+QMCDRecord.h
See attached Screenshot
<img width="733" alt="screen shot 2016-11-30 at 11 33 15 am" src="https://cloud.githubusercontent.com/assets/4178384/20747601/ac4586a0-b710-11e6-8422-c70bb0a34e0c.png">

**Comment by Raikerian** [comment]
Hi,

Well, you can clearly see the error. Why do you have a space between `(Class)` class declaration and identifier name `class`?
I don't see such problem in our project: https://github.com/QuickBlox/q-municate-ios/blob/master/Pods/QMServicesDevelopment/QMDBStorage/QMDBStorage/QMCDRecord/Categories/CoreData/NSManagedObjectModel%2BQMCDRecord.h

**Comment by ErAshu** [comment]
I have removed the space but still geting same error. See screenshot
<img width="770" alt="screen shot 2016-11-30 at 3 31 12 pm" src="https://cloud.githubusercontent.com/assets/4178384/20747950/2a48776e-b712-11e6-9903-bd62d38a0792.png">

**Comment by Raikerian** [comment]
Is your project written in swift? Try to replace `class` with `aClass`, does it help?

**Comment by ErAshu** [comment]
No, my project is written in Objective C in Xcode Version 8.1 (8B62)

**Comment by Raikerian** [comment]
Did rename help you? If not then try to reinstall pods.

**Comment by ErAshu** [comment]
I have renamed but still same issue raise.
I have manually install not from POD. Please provide pod install step.

**Comment by Raikerian** [comment]
Here is how to install with CocoaPods: https://github.com/QuickBlox/q-municate-services-ios#1-cocoapods

**Comment by ErAshu** [comment]
I have install with Cocoapods but now gettting this error.
I have create a fresh project and add these line in podfile.
pod 'QMServices'
pod 'QMChatViewController'
pod 'SearchEmojiOnString'
pod 'UIAlertView+Blocks'
pod 'Fabric'
pod 'Crashlytics'
pod 'MPGNotification'

Now getting this error
/Project/testingQM/Pods/Target Support Files/QMServices/QMServices-prefix.pch:5:9: 'Quickblox/Quickblox.h' file not found

Attaching screenshot.
<img width="1280" alt="screen shot 2016-11-30 at 8 25 47 pm" src="https://cloud.githubusercontent.com/assets/4178384/20784140/75594308-b7be-11e6-82fe-d0abdf643501.png">
Please help me out.

**Comment by VitaliyGuru** [comment]
@ErAshu, Have you fixed the issue?

**Comment by ErAshu** [comment]
Yes, I had install it by POD. This issue not regenerate but another issue.
