### ISSUE TITLE
[BITCODE] error when uploading archieve to appstore

### ISSUE THREAD

**Issue by Anilkr91** [QuickBlox/q-municate-ios#202]
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "HeartKeeper.app/Frameworks/Quickblox.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode) and arm64(bitcode). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

**Comment by Raikerian** [comment]
Hi,

Where are you getting this error?
Q-municate has bitcode disabled for now, cause it is shipped with QuickbloxWebRTC framework which is not supporting bitcode for now.

**Comment by Anilkr91** [comment]
so what is the workaround for now..

**Comment by Raikerian** [comment]
At first I need to know where are you getting this error, at least.

**Comment by Anilkr91** [comment]
i am done with making an archieve of the app but when i upload the archieve to the appstore this  error comes after few minutes.

**Comment by Anilkr91** [comment]
should i downgrade the version of the pod ...?

**Comment by Raikerian** [comment]
It wouldn't help probably in your case. Try this http://stackoverflow.com/questions/37689054/sudden-error-when-uploading-to-itunesconnect-itms-90635-invalid-mach-o-format

**Comment by VitaliyGuru** [comment]
@Anilkr91, Hello. Any updates?

**Comment by Anilkr91** [comment]
i was able to upload the binary when i deselect the use bitcode option when uploading to Appstore.. Do you have any other way around to solve the issue.

**Comment by VitaliyGuru** [comment]
@Anilkr91 , We're working on it, but, unfortunately, there is no ETA.

**Comment by Pro100Andrey** [comment]
@Anilkr91  resolved, QuickbloxWebRTC.framework supports bitcode now
