### ISSUE TITLE
Error in QMChatCacheModel bundle

### ISSUE THREAD

**Issue by Anilkr91** [QuickBlox/q-municate-ios#203]
ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/HeartKeeper.app/QMChatCacheModel.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by VitaliyGuru** [comment]
@Anilkr91 Could you please provide QMServices version?

**Comment by Anilkr91** [comment]
I have added QMServices Manually

**Comment by VitaliyGuru** [comment]
You can open folder which contains QMServices. There you can find the file with "podspec" extension.
Could you, please open this file and tell `s.version`?

**Comment by VitaliyGuru** [comment]
@Anilkr91 , Any updates?

**Comment by Anilkr91** [comment]
i have removed the  CFBundleSupportedPlatforms key from the Info.plist and it is working for me
