### ISSUE TITLE
error when pod install: target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by Anilkr91** [QuickBlox/q-municate-ios#204]
The 'Pods-HeartKeeper' target has transitive dependencies that include static binaries: (/Users/anilkumar/Desktop/ProntoITLabs/Developer/heart-keeper-ios/Pods/QuickBlox/Quickblox.framework)

**Comment by VitaliyGuru** [comment]
@Anilkr91  You should change `pod 'QuickBlox', '2.7.2'` with `pod 'QuickBlox', '2.7.5'`.

QuickBlox is released as a dynamic framework since version 2.7.5.

**Comment by Anilkr91** [comment]
Issue is resolved by including the 'QuickBlox', '2.7.5'  version . Thanks
