### ISSUE TITLE
Info needed about cocoapod of this project

### ISSUE THREAD

**Issue by singhnitesh** [QuickBlox/q-municate-ios#206]
Hi,
I wished to know if there's cocoapod for this project.
Thanks

**Comment by VitaliyGuru** [comment]
@singhnitesh , Hello. Q-municate contains next components:

- [Quickblox SDK](https://github.com/QuickBlox/quickblox-ios-sdk)
- [QMServices](https://github.com/QuickBlox/q-municate-services-ios)
- [QMChatViewController](https://github.com/QuickBlox/QMChatViewController-ios)
- [Quickblox webrtc SDK](https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API).

All these components can be installed via cocapods.

**Comment by singhnitesh** [comment]
Hi @VitaliyGuru 
I've looked at the components, love the abstraction, but my use case is very similar to your Qmunicate implementation where all these components come together and shine. My project is in swift to which I need to add chat functionality and I was hoping I wouldn't have to re-invent the wheel and I could like extend only certain classes from this project only. 
Anyways, thanks for the info, I would try adding Qmunicate in my app as a submodule or if I get enough time then attempt to create a pod :)
