### ISSUE TITLE
Chat failed to connect.not authorized.passowrd not verified issue: Q-municate iOS(v2.2.1) issue

### ISSUE THREAD

**Issue by Uday-1985** [QuickBlox/q-municate-ios#210]
Hi There,

I am facing Chat failed to connect issues in iOS q-municate project(v2.2.1).Please find the attached details.Feel free to reach me for any additional details.

![chat failed to connect](https://cloud.githubusercontent.com/assets/14942241/22724609/4872e1fe-eded-11e6-8d42-59990822fe8f.PNG)

Thanks,

**Comment by Uday-1985** [comment]
Hi Pro100Andrey,

Have you found a fix for this error?.

**Comment by Pro100Andrey** [comment]
Hi @Uday-1985,   Please find comments below: 
 1. You provided a screenshot of client side application, that looks similar to Q-municate, but is not a Q-municate.
   2. Q-municate application v 2.2.1 is outdated. Please update Q-municate code up to latest version and test if issue occur.
   3. Please keep in mind that Q-municate application is a separate product and is not a part of QuickBlox core functionality.  QuickBlox core team doesn’t provide consultancy on custom implementation. It you need any help with Q-municate implementation/ debugging - please reach sales team (Professional services team).   PS Please don’t share internal information (logs) via github and use customer portal for this purpose.
