### ISSUE TITLE
Error: Build Issue in QMMessagesMemoryStorage.m file

### ISSUE THREAD

**Issue by nikunjazilen** [QuickBlox/q-municate-ios#211]
Hi,
I want to integrate chat and video feature into my app using this demo but while I installed the `pod 'QuickBlox', '~> 2.9'` and getting the so many errors in `QMMessagesMemoryStorage.m` file. 

Build Errors
```
//Expected type error
- (void)addMessage:(QBChatMessage *)message forDialogID:(NSString *)dialogID;
//Expected )
- (void)addMessages:(NSArray QB_GENERIC(QBChatMessage *) *)messages forDialogID:(NSString *)dialogID;
//Expected )
- (void)replaceMessages:(NSArray QB_GENERIC(QBChatMessage *) *)messages forDialogID:(NSString *)dialogID;
//Expected a type
- (void)updateMessage:(QBChatMessage *)message;
//Expected )
- (NSArray QB_GENERIC(QBChatMessage *) *)messagesWithDialogID:(NSString *)dialogID;
```
Can you help me to resole this issue?

Thanks

**Comment by VitaliyGuru** [comment]
@nikunjazilen, Hello. What version of QMServices are you using?

**Comment by nikunjazilen** [comment]
Hi,

Thanks for the reply. Issue has been resolve after installed Pod QMServices. Before that I just copy the files from source code and paste it and I think it was in under development. I am using latest pod version of QuickBlox 2.9.1

Now, I m facing other build errors in the QBChatMessage+QMCallNotifications.m class file. There are so many errors in this class.

```
//Cannot find interface declaration for 'QBChatMessage'
@implementation QBChatMessage (QMCallNotifications)

//Property callNotificationType not found on object of type 'const
return (self.callNotificationType != QMCallNotificationTypeNone
            && self.callNotificationState != QMCallNotificationStateNone);

//No known instance method for selector '_context'
return [[self _context][kQMCallNotificationTypeKey] integerValue];
```

Can you please help me to resolve this issue?

Thanks

**Comment by VitaliyGuru** [comment]
@nikunjazilen, Try to import QBUpdateUserParameters category in the QMTasks.m class file or pch file of the project. 
```objective-c
    #import "QBUpdateUserParameters+CustomData.h"
```
BTW It's better to start with sample. []

**Comment by nikunjazilen** [comment]
Hi,

Still getting error in the below file.

@implementation QBUpdateUserParameters (CustomData)
//Property implementation must have its declaration in the category 'CustomData'
@dynamic avatarUrl;
@dynamic status;
@dynamic isImport;

Thanks

**Comment by VitaliyGuru** [comment]
@nikunjazilen, Hello. Have you resolved this issue?
