### ISSUE TITLE
Custom Q-municate implementation error

### ISSUE THREAD

**Issue by videhjaiswal** [QuickBlox/q-municate-ios#213]
NSParameterAssert([QMCore instance].currentProfile.userData); always crash on this line ...

**Comment by VitaliyGuru** [comment]
@videhjaiswal, Hello. What Q-municate version are you using? Have you made changes in the project?

**Comment by videhjaiswal** [comment]
![screen shot 2017-02-16 at 12 22 11 pm](https://cloud.githubusercontent.com/assets/25812816/23011311/4a2e83cc-f446-11e6-9a7a-0977e53bdded.png)
![screen shot 2017-02-16 at 12 46 21 pm](https://cloud.githubusercontent.com/assets/25812816/23011319/5c773236-f446-11e6-8c71-6e52dd357729.png)
 I am Using Qmunicate 2.0

**Comment by videhjaiswal** [comment]
What i do to resolve this crash......

**Comment by VitaliyGuru** [comment]
@videhjaiswal,  As for first crash: Q-municate application v 2.0 is outdated. Please update Q-municate code to the latest version and test if the issue occurs.

What version of QMServices are you using?

**Comment by VitaliyGuru** [comment]
Closed due to a lack of response.
