### ISSUE TITLE
Photos not being shown on q-municate chat app

### ISSUE THREAD

**Issue by rcorin** [QuickBlox/q-municate-ios#214]
There is a 500 server error: 

2017-02-28 17:38:02.771521 Q-municate[49057:12368391] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170429d00> { URL: https://qbprod.s3.amazonaws.com/ } { status code: 500, headers {
    Connection = close;
    "Content-Type" = "application/xml";
    Date = "Tue, 28 Feb 2017 20:38:02 GMT";
    Server = AmazonS3;
    "Transfer-Encoding" = Identity;
    "x-amz-id-2" = "OTaefrYWKfRspJgrrrh0G/TcwNEarta4gQmd6HXTV73TOnSFY4Wz3kl7so2dse9S6FqxUn/lpEM=";
    "x-amz-request-id" = 934370ED267447E4;
} }, NSErrorFailingURLKey=https://qbprod.s3.amazonaws.com/, com.alamofire.serialization.response.error.data=<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d225554 462d3822 3f3e0a3c 4572726f 723e3c43 6f64653e 496e7465 726e616c 4572726f 723c2f43 6f64653e 3c4d6573 73616765 3e576520 656e636f 756e7465 72656420 616e2069 6e746572 6e616c20 6572726f 722e2050 6c656173 65207472 79206167 61696e2e 3c2f4d65 73736167 653e3c52 65717565 73744964 3e393334 33373045 44323637 34343745 343c2f52 65717565 73744964 3e3c486f 73744964 3e4f5461 65667259 574b6652 73704a67 72727268 30472f54 63774e45 61727461 3467516d 64364858 54563733 544f6e53 46593457 7a336b6c 37736f32 64736539 53364671 78556e2f 6c70454d 3d3c2f48 6f737449 643e3c2f 4572726f 723e>, NSLocalizedDescription=Request failed: internal server error (500)}
2017-02-28 17:38:02.776752 Q-municate[49057:12368391] [QBCore] Response error reasons: (null)

**Comment by rcorin** [comment]
In the console under Content it appears the action, with status "Not uploaded"

**Comment by soulfly** [comment]
We are currently experiencing AWS outage
More info here on status https://status.aws.amazon.com/
