### ISSUE TITLE
QMcore Crash

### ISSUE THREAD

**Issue by VaibhavMehta25Feb** [QuickBlox/q-municate-ios#217]
I have used "Q-municate" code into my test app , I am able to compile the code. But while running the code my app is crashing at 
[QMContactListCache setupDBWithStoreNamed:kQMContactListCacheNameKey applicationGroupIdentifier:[self appGroupIdentifier]]; 
in QMCore class.
Can you please help me in resolving this issue, also if you can let me know all steps to integrate Q-municate app in to my app directly, and customise it.

Logs for your reference :

2017-05-08 11:28:03.185868 TestChat[1585:38748] [MC] Reading from private effective user settings.
2017-05-08 11:28:20.994 TestChat[1585:38748] Init - QMAuthService service...
2017-05-08 11:28:20.994 TestChat[1585:38748] Init - QMChatService service...
2017-05-08 11:28:20.999 TestChat[1585:38802] [QBCore] Restoring QBSession, status = -25300. See "Security Error Codes" (SecBase.h)
2017-05-08 11:28:21.003 TestChat[1585:38748] Init - QMUsersService service...
2017-05-08 11:28:21.003 TestChat[1585:38748] +[QMContactListCache setupDBWithStoreNamed:applicationGroupIdentifier:]: unrecognized selector sent to class 0x10fb20d90
2017-05-08 11:28:21.007 TestChat[1585:38748] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[QMContactListCache setupDBWithStoreNamed:applicationGroupIdentifier:]: unrecognized selector sent to class 0x10fb20d90'
*** First throw call stack:
(
0 CoreFoundation 0x0000000115fd734b __exceptionPreprocess + 171
1 libobjc.A.dylib 0x0000000115a3f21e objc_exception_throw + 48
2 CoreFoundation 0x0000000116046e74 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3 CoreFoundation 0x0000000115f5cc15 ___forwarding___ + 1013
4 CoreFoundation 0x0000000115f5c798 _CF_forwarding_prep_0 + 120
5 TestChat 0x000000010f06144e -[QMCore init] + 174
6 TestChat 0x000000010f061362 __18+[QMCore instance]_block_invoke + 50
7 libdispatch.dylib 0x0000000116aa20cd _dispatch_client_callout + 8
8 libdispatch.dylib 0x0000000116a871fc dispatch_once_f + 501
9 TestChat 0x000000010f061308 +[QMCore instance] + 136
10 TestChat 0x000000010eff595c -[QMLogInViewController done:] + 1452
11 UIKit 0x0000000112fcd5b8 -[UIApplication sendAction:to:from:forEvent:] + 83
12 UIKit 0x000000011340e405 -[UIBarButtonItem(UIInternal) _sendAction:withEvent:] + 149
13 UIKit 0x0000000112fcd5b8 -[UIApplication sendAction:to:from:forEvent:] + 83
14 UIKit 0x0000000113152edd -[UIControl sendAction:to:forEvent:] + 67
15 UIKit 0x00000001131531f6 -[UIControl _sendActionsForEvents:withEvent:] + 444
16 UIKit 0x0000000113153380 -[UIControl _sendActionsForEvents:withEvent:] + 838
17 UIKit 0x00000001131520f2 -[UIControl touchesEnded:withEvent:] + 668
18 UIKit 0x000000011303ace1 -[UIWindow _sendTouchesForEvent:] + 2747
19 UIKit 0x000000011303c3cf -[UIWindow sendEvent:] + 4011
20 UIKit 0x0000000112fe963f -[UIApplication sendEvent:] + 371
21 UIKit 0x00000001137db71d __dispatchPreprocessedEventFromEventQueue + 3248
22 UIKit 0x00000001137d43c7 __handleEventQueue + 4879
23 CoreFoundation 0x0000000115f7c311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
24 CoreFoundation 0x0000000115f6159c __CFRunLoopDoSources0 + 556
25 CoreFoundation 0x0000000115f60a86 __CFRunLoopRun + 918
26 CoreFoundation 0x0000000115f60494 CFRunLoopRunSpecific + 420
27 GraphicsServices 0x00000001181f5a6f GSEventRunModal + 161
28 UIKit 0x0000000112fcb964 UIApplicationMain + 159
29 TestChat 0x000000010eff1e3f main + 111
30 libdyld.dylib 0x0000000116aee68d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by VitaliyGuru** [comment]
@VaibhavMehta25Feb, Could you please specify the branch(or commit) of Q-municate source code and QMServices version?
