### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by dungnc** [QuickBlox/q-municate-ios#235]
Hi, my app is working well until 07/28/2017
I'm check in "Queue" at Admin page and it's show me: 
[https://gyazo.com/0f1e37f0d461eb2c54ee4c3966cd9529](url)
My app id is: 49976

Please help me, thanks for your supporting

**Comment by Raikerian** [comment]
Hi, please stick to one issue: https://github.com/QuickBlox/quickblox-ios-sdk/issues/842
