### ISSUE TITLE
Logout throwing uncaught exception of type NSException

### ISSUE THREAD

**Issue by kittlsk** [QuickBlox/q-municate-ios#241]
I downloaded the ios app and replaced the app credentials as instructed in https://quickblox.com/developers/Q-municate#Q-municate_iOS

The following exception thrown whenever Logout is clicked:
libc++abi.dylib: terminating with uncaught exception of type NSException

And the following line under the function main() in q-municate-ios-master/Q-municate/Supporting Files/main.m gets highlighted:
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([QMAppDelegate class]));

Anyone else is facing the similar issue?

p/s I also noticed that the above error happens when we click on Settings -> Profile Image -> Take Image

**Comment by VitaliyGuru** [comment]
@kittlsk, Please add full logs, also add exception breakpoint and send us the call stack on the crash.

**Comment by kittlsk** [comment]
Attached please find full log and screen capture on the error break point.

<img width="1280" alt="screen shot 2017-09-19 at 8 49 37 am" src="https://user-images.githubusercontent.com/1089095/30571042-a064bcc8-9d17-11e7-9586-1273e4552146.png">

[log.txt](https://github.com/QuickBlox/q-municate-ios/files/1312710/log.txt)

**Comment by VitaliyGuru** [comment]
@kittlsk  This crash is fixed in the lastest Quickblox SDK version.
