### ISSUE TITLE
Chats are not being saved in Core data

### ISSUE THREAD

**Issue by krishnads** [QuickBlox/q-municate-ios#258]
I am using Qmunicate to develop my own app. I am not able to get chats offline from core data. Getting the following error.

error: -executeRequest: encountered exception = I/O error for database at /Users/latika/Library/Developer/CoreSimulator/Devices/49C916CC-FDF0-46EA-BD7B-9D73B3F168C9/data/Containers/Data/Application/7FB3534D-EC37-4BE1-A525-F8FCBA44D62C/Library/Application Support/Q-municate/sample-cache.  SQLite error code:6922, 'disk I/O error' with userInfo = {
    NSFilePath = "/Users/latika/Library/Developer/CoreSimulator/Devices/49C916CC-FDF0-46EA-BD7B-9D73B3F168C9/data/Containers/Data/Application/7FB3534D-EC37-4BE1-A525-F8FCBA44D62C/Library/Application Support/Q-municate/sample-cache";
    NSSQLiteErrorDomain = 6922;
}

**Comment by Pro100Andrey** [comment]
Hi @krishnads, reset your simulator, and try again

**Comment by krishnads** [comment]
Thanks. It Worked...
