### ISSUE TITLE
Localization Auth.storyboard

### ISSUE THREAD

**Issue by gbr33** [QuickBlox/q-municate-ios#272]
Hi
I got 2 Errors when I Localization Auth.storyboard
IB Designables Group
1- /Scenes/Auth/Base.lproj/Auth.storyboard: error: IB Designables: Failed to render and update auto layout status for QMWelcomeScreenViewController (ncs-B4-uAJ): Failed to load designables from path (null)

2- /Scenes/Auth/Base.lproj/Auth.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

Thanks for your support

Regards
Allan

**Comment by VitaliyGuru** [comment]
@gbr33, This issue is not related to our SDK and Q-municate. This is a Xcode's bug.
Just 
- remove derived data.
- restart the Xcode for now.
- clean project
for now.
