### ISSUE TITLE
Chat dialogs list screen does not list any previous chat history after clearing app from device memory

### ISSUE THREAD

**Issue by kittlsk** [QuickBlox/q-municate-ios#275]
I downloaded the latest iOS app and found out that the Chat dialogs list screen doesn't list any previous chat history after clearing the app from device memory.  I would need to go to Contacts screen, and click on individual contact and Send message link to retrieve the existing chat history, then go back to Chats screen and the chat history will then appear.  

Logout and relogin doesn't have this issue but after clearing the app from the device memory, this issue occurs.  I'm testing with my connected iPhone 7 in Xcode.

Anyone else is facing this issue?

**Comment by VitaliyGuru** [comment]
@kittlsk, We have tested described behavior and haven't faced this issue. 
Please add full logs and any helpful information to reproduce this issue.
