### ISSUE TITLE
Digits localization not loading

### ISSUE THREAD

**Issue by gbr33** [QuickBlox/q-municate-ios#277]
Hi 
After localizing and testing login with phone Digits not loading the localization language it show in English only, tested on simulator and iPhone 4 , 4s

![screen shot 22 sep 2017 9 49 15 am](https://user-images.githubusercontent.com/18315898/30735146-335d35c4-9f7e-11e7-804b-fbad532719d9.png)

Thanks

**Comment by VitaliyGuru** [comment]
@gbr33, The Digits SDK will be retired on September 30, 2017. Q-municate has been migrated to Firebase. [More info] (https://get.digits.com/blog/introducing-firebase-phone-authentication).
