### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by anil03** [QuickBlox/q-municate-ios#290]
I downloaded the project Q-municate-ios. I tried to run the project and when i entered the Phone number. It shows the error "Something went wrong, Please try again later". 

Please see the screen shot.
![simulator screen shot - iphone 8 plus - 2017-11-13 at 17 58 04](https://user-images.githubusercontent.com/602883/32725736-3b84b870-c89c-11e7-9e3e-981be2dfa032.png)

**Comment by VitaliyGuru** [comment]
@anil03, Hello, You have tried to test on the simulator, haven't you? Try it again with the real device.

**Comment by anil03** [comment]
Yes, I tried on the Simulator.

**Comment by VitaliyGuru** [comment]
@anil03, Please try again on the device. In our case, Firebase verification is based only on silent APNs notifications, so you can't be logged in via Firebase on the simulator.

**Comment by anil03** [comment]
I tried on device.
I tried on iPhone 6s and I am able to login.
but when I am trying to another device such iPhone SE. I am getting the same error "Something went wrong".
