### ISSUE TITLE
How to check contact into chat

### ISSUE THREAD

**Issue by anil03** [QuickBlox/q-municate-ios#292]
Hi,
I am using the Q-municate-iOS chat application for may project.
I created the account into QB and I am able to run the project. 
When I signed in through two mobile number in same device but I am confuse how to chat. I am not getting other contact into my Contact list of app.
Everything looks like blank.

Please let me know any error

**Comment by VitaliyGuru** [comment]
@anil03, You should add each other to the contact list by searching in the 'global search', adding as the friend and confirming 'friend request'.
