### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by shahkevin23** [QuickBlox/q-municate-ios#293]
After replacing the credentials still i'm able to login into.
Please guide me 
![screen shot 2017-12-05 at 6 30 17 pm](https://user-images.githubusercontent.com/24786934/33608567-eda36ef2-d9ea-11e7-9c27-d032c5369849.png)

**Comment by VitaliyGuru** [comment]
@shahkevin23, 
Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by VitaliyGuru** [comment]
@shahkevin23, Any updates?

**Comment by shahkevin23** [comment]
Apology for late response

**Comment by VitaliyGuru** [comment]
@shahkevin23, Your logs aren't full. Please add full logs.
