### ISSUE TITLE
Can I customise the Login with Phone UI Using Firebase.

### ISSUE THREAD

**Issue by anil03** [QuickBlox/q-municate-ios#295]
I am trying to use the q-municate app for my custom. chat.

I need to log in with Phone Only. Is it possible to use the FIREBASE and My own custom UI for the registration?

Please see the image
![whatsapp image 2017-12-08 at 3 42 43 pm](https://user-images.githubusercontent.com/602883/33761344-ad76685c-dc2e-11e7-9b1c-c1f2ddf2a29a.jpeg)
![whatsapp image 2017-12-08 at 3 43 38 pm](https://user-images.githubusercontent.com/602883/33761410-e8c8f410-dc2e-11e7-8374-e4d441c0ae4f.jpeg)

**Comment by Pro100Andrey** [comment]
Q: I need to log in with Phone Only. Is it possible to use the FIREBASE and My own custom UI for the registration?

A: yes shure.
