### ISSUE TITLE
After closing app and re-opening, previous chats disappear

### ISSUE THREAD

**Issue by martyndix** [QuickBlox/q-municate-ios#301]
When I close the app and re-open it, my previous chats disappear. If I log out then log in again, they come back. All the time the chats and contacts etc remain visible in QuickBlox. 
Any assistance with this much appreciated.
Thanks,
Martyn.

**Comment by VitaliyGuru** [comment]
Please use the last version of Q-municate. Have you performed any custom changes?

**Comment by martyndix** [comment]
I am using the latest version and not made any custom changes.

**Comment by VitaliyGuru** [comment]
Could please take the last version of Q-municate from the dev branch? And please delete the app before installing and use your credentials.

**Comment by VitaliyGuru** [comment]
If it doesn't help please add full logs. 

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by VitaliyGuru** [comment]
@martyndix, Any updates?

**Comment by martyndix** [comment]
I'm still having the problem but only with iOS. I am not really sure what I am doing to be honest. 
What do I do with: 
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];

Please explain what I do with this.
Thanks,
Martyn.

**Comment by VitaliyGuru** [comment]
You should add this code to AppDelegate's method 'didFinishLaunching '

**Comment by rab211** [comment]
Hello, i have the same problem i added the [QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging]; in the appdelegate.m but nothing, can you tell me what is the problem ?
Thank you 
Antonios
