### ISSUE TITLE
iOS v2.7

### ISSUE THREAD

**Issue by martyndix** [QuickBlox/q-municate-ios#316]
Hello,
I have just tried to use the new version of Q-municate in Xcode however when I go to the file: AppDelegate.m there is no option on line 20 to enter the quickblox numbers such as app ID, authorisation key etc.
Please can someone help me with where I need to enter these values to connect the app to my QuickBlox?
Many thanks,
Martyn.

**Comment by Pro100Andrey** [comment]
Hi @martyndix, any updates?

Thanks

**Comment by martyndix** [comment]
Thanks Andrey, all sorted!
Your help is very much appreciated.
Martyn.
