### ISSUE TITLE
App Store Binary Rejected - Guideline 1.2 - Safety - User Generated Content

### ISSUE THREAD

**Issue by gbr33** [QuickBlox/q-municate-ios#320]
Hi
After submitting your original 2.6 release on App Store it get rejected here what they wrote to me :
-------------------------------------
Binary Rejected

Guideline 1.2 - Safety - User Generated Content

Your app enables the display of user-generated content but does not have the proper precautions in place.

Next Steps

To resolve this issue, please revise your app to implement all of the following precautions:

- Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
- A method for filtering objectionable content
- A mechanism for users to flag objectionable content
- A mechanism for users to block abusive users
- The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

-------------------------------------------------
any help please Thanks

**Comment by gbr33** [comment]
I got a new respond from App Store Review says :
------------------------
- Thank you for your response. To clarify, while our App Store Review Guidelines is a living document and subject to change, all social networking apps are subject to meet compliance with guideline 1.2.0.

In order for your app to be reconsidered for the App Store, it would be appropriate to bring your app into compliance.

Best regards, 
App Store Review
---------------------------

So are you goanna implement these features in your next update ?

Thanks for your support
Regards

**Comment by Raikerian** [comment]
Hi @gbr33 

It seems like you need to add some kind of "report abuse" button. Add it to a profile, so any user can report another user for some kind of misbehaviour. Make that button to send a user-input text to any of you email or system user, for example.
We haven't met such requirements in Q-municate yet, but will surely add it in a future if needed.

For now you have to implement that feature by yourself.
