### ISSUE TITLE
How to customise whole QMChatCell ?

### ISSUE THREAD

**Issue by MiteshiOS** [QuickBlox/q-municate-ios#329]
Please let me know how can i customise whole QMChatCell. Also in demo on tap of cell full view of cell is appear but i didn't want like that. I want separate message and status in cell. Also provide me suggestion in a way that so i can add some more info if require in future. Also i want to customise chat bubble, let me know is it possible or not. Please review the attached screenshot for more information.
![screen shot 2018-03-13 at 3 01 17 pm](https://user-images.githubusercontent.com/17427703/37393313-c2b08ee2-2796-11e8-937c-6f5eb0ca9bd1.png)

**Comment by Pro100Andrey** [comment]
Hi @MiteshiOS, check this answer https://github.com/QuickBlox/quickblox-ios-sdk/issues/961
