### ISSUE TITLE
How to implement CallKit while app is in Background or Kill ?

### ISSUE THREAD

**Issue by testingmyaccount** [QuickBlox/q-municate-ios#330]
In demo code i found that CallKit incoming call screen is appear when app is active, but nothing happen except notification while doing call when recipient app is in background or kill. Can you please help me on this how can i achieve this. I am familiar with Twilio and Sinch and i know they provides methods which works at the time of call when app is in background or kill. 
Is there any extra set up i need to do i.e VOIP or anything else ? 
Please help me on this as soon as possible.

**Comment by Pro100Andrey** [comment]
Duplicate https://github.com/QuickBlox/quickblox-ios-sdk/issues/970
