### ISSUE TITLE
Push Notification not working when App is not running.

### ISSUE THREAD

**Issue by kushal211** [QuickBlox/q-municate-ios#332]
Hello,

I've clone this repo. Change the account detail and uploaded the iOS push certificate in the admin panel.

When the app is not running or in the background, the push notification for the messages are not coming. I've tried sending push notification from the QB dashboard and it is working perfect but not for the messages. 

I've tried with the audio and video call, the push is coming but the application is crashing in `handlePushNotificationWithDelegate` method in **QMPushNotificationManager.m** file as the payload does not have the dialogID.

I'm testing it with the sandbox and certificate is also uploaded same.

**Comment by pro100andrey** [comment]
Hi @kushal211, 

1) Please remove all certificates and create the new one. It should be Universal (Sandbox & Production & VoIP) SSL certificate.

2)  Did you have any errors in "admin panel" -> Push notifications -> Queue?

3) Try checking certificate error logs also.
![image](https://user-images.githubusercontent.com/4947664/38208235-0cbd5142-36b9-11e8-9a17-c73fab089d11.png)

3) Could you provide full logs with gist.github.com?

Thanks.

**Comment by pro100andrey** [comment]
@kushal211 For enable logs use code below:

```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by kushal211** [comment]
Hi @pro100andrey ,

Thanks for the reply.

1. Please remove all certificates and create the new one. It should be Universal (Sandbox & Production & VoIP) SSL certificate.
- Yes, Certificate is created new and uploaded again as well.

2. Did you have any errors in "admin panel" -> Push notifications -> Queue?
- Messages are not even displayed in the Queue as well. (Check the attached image)
![screen shot 2018-04-03 at 2 13 23 pm](https://user-images.githubusercontent.com/24749866/38240208-9c3c19fa-374c-11e8-919c-8628ecec3d66.png)

3. Try checking certificate error logs also.
- No error log in the file. (Attached the log file)
[apns-development.log](https://github.com/QuickBlox/q-municate-ios/files/1870840/apns-development.log)

4. Could you provide full logs with gist.github.com?
- I did not get you here. Sorry. Which logs do you want?

**Comment by pro100andrey** [comment]
@kushal211 

> Did you have any errors in "admin panel" -> Push notifications -> Queue?

Tap on sent status and check again.

> I did not get you here. Sorry. Which logs do you want?

Could you provide your application id and bundle identifier

**Comment by kushal211** [comment]
> Did you have any errors in "admin panel" -> Push notifications -> Queue?
All the five are with this status - **APNS (Apple Push) Delivered: 1, failed: 0** 

applicationID: 69786
bundleID: com.indianic.securechatapp

**Comment by pro100andrey** [comment]
@kushal211 

I need more time to investigate.

Thanks.

**Comment by kushal211** [comment]
Hi @pro100andrey ,

It is started working. I actually don't know how but the last change which I made in admin panel was to re-enable **Enable automatic notifications for offline users** from the Chat > Alerts.

I've first disabled it and then enable it again. And the push notification has started working fine.

Thank you for the support.
