### ISSUE TITLE
After closing app and re-opening, all chats disappear on Chat Dialogs List 

### ISSUE THREAD

**Issue by rab211** [QuickBlox/q-municate-ios#333]
Hello, i have this problem i added the [QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging]; in the appdelegate.m but not fixed, can you tell me what is the problem ? and how to fix i am new i dont know very good !!
Thank you
Antonios

**Comment by pro100andrey** [comment]
Hi @rab211  Could you please provide full logs?

**Comment by pro100andrey** [comment]
To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by pro100andrey** [comment]
Hi, @rab211 Any updates?
