### ISSUE TITLE
VOIP Push not working for Android to iOS when app is not running

### ISSUE THREAD

**Issue by kushal211** [QuickBlox/q-municate-ios#339]
Hi,

I'm facing one issue with a specific case where I'm calling **to iOS** user **from Android** device and application is in the **background** in iOS, the push notification is not coming to the iOS device and it is also not showing in Admin panel "Queue" section.

All the other cases are working fine. I'm using [Q-municate-android](https://github.com/QuickBlox/q-municate-android) for the Android application.

Please help me with this specific case.

Note: I've tried sending VOIP push from the dashboard and it is working fine.

Thank you.

**Comment by kushal211** [comment]
Hi, 

Yes I've log enabled and there are many logs generated in console. It is all working fine and perfect for iOS to iOS, iOS to Android. Just in case of Android to iOS. 

Should I send you the logs from iOS ?

**Comment by VitaliyGuru** [comment]
@kushal211, 
Could you please check that event's payload from android contains:
"VOIPCall" : "1"?

**Comment by VitaliyGuru** [comment]
@kushal211, Could you please print event(all keys and values) that you are sending from android?

**Comment by kushal211** [comment]
hi @VitaliyGuru ,

Yes, I've checked that thing and it was missing in Android app. So I've added that in the payload.

Here is the complete payload from the Android app:

```
{
    message_type=push_type_call,
    VOIPCall=1,
    friends=[
      49554268
    ],
    message=leesaiscallingyou!,
    ios_voip=1
 }
```

Please note that I've added one extra key as well **ios_voip** and also tried with all the possible combination of the keys by removing them one by one but none of them got me success.

It is not even adding the push notification in the Queue of the push notification in my dashbaord.

**Comment by VitaliyGuru** [comment]
@kushal211, Please provide code for creating the event with `VOIPCall=1`  in Android?

**Comment by kushal211** [comment]
Hi @VitaliyGuru ,

Here is the code I'm using in Android:

```
Public class CoreNotificationHelper {

    public static QBEvent createPushEvent(List<Integer> userIdsList, String message, String messageType) {
        StringifyArrayList<Integer> userIds = new StringifyArrayList<Integer>();
        userIds.addAll(userIdsList);
        QBEvent event = new QBEvent();
        event.setUserIds(userIds);
        event.setEnvironment(QBEnvironment.DEVELOPMENT);
        event.setNotificationType(QBNotificationType.PUSH);
        event.setPushType(QBPushType.GCM);

        // Custom - For iOS VOIP Push
        event.setPushType(QBPushType.APNS_VOIP);

        setMessage(event, message, messageType);
        return event;
    }

    private static void setMessage(QBEvent event, String message, String messageType) {
        if (!setMessageWithTypeIfNeed(event, message, messageType)) {
            event.setMessage(message);
        }
    }

    private static boolean setMessageWithTypeIfNeed(QBEvent event, String message, String messageType) {
        if (!TextUtils.isEmpty(messageType)) {
            HashMap<String, Object> data = new HashMap<>();
            data.put("data.message", message);
            data.put("data.type", messageType);

            // Custom - For iOS VOIP Push
            data.put("data.message","1" );
            data.put("data.type", "ios_voip");

            data.put("data.message","1" );
            data.put("data.type", "VOIPCall");

            event.setMessage(data);
            return true;
        }
        return false;
    }

}
```

Note:
You can check the code which is commented as **Custom - For iOS VOIP Push** which I've added in  **CoreNotificationHelper** class

**Comment by kushal211** [comment]
Hi @VitaliyGuru , 

Any update on the code provided?

**Comment by VitaliyGuru** [comment]
@kushal211, Please use the code from the [Android Q-municate](https://github.com/QuickBlox/q-municate-android/blob/62976920e8d200d3a402d87f14029f3b5693ca39/Q-municate_core/src/main/java/com/quickblox/q_municate_core/utils/helpers/CoreNotificationHelper.java#L19).
And in the method `createPushEvent` you should provide `PUSH_MESSAGE_TYPE_CALL` for `messageType` parameter and set the appropriate environment.

**Comment by VitaliyGuru** [comment]
@kushal211, Any updates?

**Comment by leena12345** [comment]
Hi @VitaliyGuru ,

In android,  sometimes, Chat history screen contains duplicate data in listview .. (Class :DialogsListFragment )
Thanks

**Comment by Raikerian** [comment]
Hi @leena12345 

This is an iOS-only repository and we have nothing to do with android code.
Please report all android issue to Quickblox Android repository here: https://github.com/QuickBlox/quickblox-android-sdk/issues
