### ISSUE TITLE
SDK 2.3

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/q-municate-ios#4]
Hi,

Since there was a major upgrade from Quickblox to version 2.3, is upgrading the code to that version planned?

Thanks

Wouter

**Comment by soulfly** [comment]
Yes, it's now in dev phase, going to release it in the mid of July with additional features

**Comment by woutergoossens** [comment]
Great! Thanks

**Comment by woutergoossens** [comment]
Any update here? Is there already a new release available?

**Comment by thiemdv** [comment]
I'm expecting the new release too.

Thanks for your great work.

**Comment by Raikerian** [comment]
Q-municate with Quickblox iOS SDK 2.4.6 is available for download.
